name: On Push master
triggers:
  github:
    secret: test
    events:
      - eventName: push
env:
  name: Heimanba
  age: 30
steps:
  - run: echo 'Hi {{ env.name }}'
  - run: echo 'Hi {{ env.name }}'
    env:
      name: Tony
  - run: echo 'Hi {{ task_id }}'
  - run: echo 'Hi {{ app.user_name }}'
  - run: echo 'Hi {{ git.event_name }}'
  - run: echo 'suceess end ===='
